version: '3'
services:
  elasticsearch:
    container_name: managerc_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      'xpack.security.enabled': 'false'
      'http.host': '0.0.0.0'
      'transport.host': '127.0.0.1'
    ports:
      ["9200:9200"]
    hostname: "elasticsearch"
    volumes:
      - esdata1:/user/share/elasticsearch/data

volumes:
  esdata1:
    driver: local
      
